# Generated by Django 2.2.3 on 2019-08-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skctapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='academics',
        ),
        migrations.AddField(
            model_name='department',
            name='academics',
            field=models.ManyToManyField(to='skctapp.Academics'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='bp',
        ),
        migrations.AddField(
            model_name='department',
            name='bp',
            field=models.ManyToManyField(to='skctapp.BestPratices'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
