# Generated by Django 2.2.3 on 2019-08-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skctapp', '0002_auto_20190808_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='certificate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
